[project]
name = "test-tech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "baml-py==0.204.0",
    "fastapi>=0.116.1",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.7",
]
