# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Chosen_Theme": types.Chosen_Theme,
    "stream_types.Chosen_Theme": stream_types.Chosen_Theme,

    "types.Classification": types.Classification,
    "stream_types.Classification": stream_types.Classification,

    "types.Completed_Form": types.Completed_Form,
    "stream_types.Completed_Form": stream_types.Completed_Form,

    "types.Contact_Info": types.Contact_Info,
    "stream_types.Contact_Info": stream_types.Contact_Info,

    "types.Contact_Properties": types.Contact_Properties,
    "stream_types.Contact_Properties": stream_types.Contact_Properties,

    "types.Personal_Info": types.Personal_Info,
    "stream_types.Personal_Info": stream_types.Personal_Info,

    "types.Personal_Properties": types.Personal_Properties,
    "stream_types.Personal_Properties": stream_types.Personal_Properties,

    "types.Properties": types.Properties,
    "stream_types.Properties": stream_types.Properties,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,


    "types.Gender": types.Gender,

    "types.Preferred_Contact_Method": types.Preferred_Contact_Method,

}